--PRODUCT PERFORMANCE
--TOTAL Number of products sold
SELECT product,
Units_Sold = COUNT(product)
FROM salespipeline
WHERE deal_stage = 'Won'
GROUP BY product
ORDER BY 1 DESC
--NetProfit
SELECT sp.product,
Net_profit = SUM(sp.close_value) - SUM(pr.sales_price)
FROM salespipeline sp
JOIN products pr
ON sp.product = pr.product
WHERE deal_stage = 'Won'
GROUP BY sp.product
ORDER BY 1 DESC

--Monthly
SELECT product
	  ,Units_Sold = COUNT(product)
	  ,[Month] = MONTH(close_date)
FROM salespipeline
WHERE deal_stage = 'Won'
GROUP by product,close_date
ORDER BY 2 DESC

/*1. Monthly Performance to show revenue growth on products*/
SELECT pr.product
	  ,Revenue_generated = SUM(sp.close_value)
	  ,[Avg_Revenue] = AVG(sp.close_value)
	  ,[Month] = MONTH(sp.engage_date)
FROM products pr
JOIN salespipeline sp
ON pr.product = sp.product
WHERE deal_stage = 'Won'
GROUP BY pr.product,sp.engage_date
ORDER BY 2 DESC

SELECT pr.product
	  ,Revenue_generated = SUM(sp.close_value)
	  ,[Avg_Revenue] = AVG(sp.close_value)
	  ,sp.close_date
FROM products pr
JOIN salespipeline sp
ON pr.product = sp.product
WHERE deal_stage = 'Won'
GROUP BY pr.product,sp.sales_agent,sp.close_date
ORDER BY 2 DESC

/*2. Performance based on revenue*/
SELECT  pr.product
	   ,Deal_Revenue =SUM(sp.close_value)
	   ,Expected_Revenue =SUM(pr.sales_price)
	   ,[Avg_Revenue] = AVG(sp.close_value)
	   ,Net_Profit = ROUND(((SUM(sp.close_value))-(SUM(pr.sales_price))*1.0),4)
	   
FROM salespipeline sp
JOIN salesteams st
ON sp.sales_agent = st.sales_agent
JOIN products pr
ON sp.product = pr.product
WHERE sp.deal_stage = 'Won'
GROUP BY pr.product
ORDER BY Deal_Revenue DESC

/*3. Performance based on product count and opportunity*/
SELECT sp. deal_stage
	  ,[GTX Pro] = COUNT(CASE WHEN pr.product='GTX Pro' THEN 1
									END)
	  ,[GTX Plus Pro] = COUNT(CASE WHEN pr.product='GTX Plus Pro' THEN 1
									END)
	  ,[MG Advanced] = COUNT(CASE WHEN pr.product='MG Advanced' THEN 1
									END)
	  ,[GTX Plus Basic] = COUNT(CASE WHEN pr.product='GTX Plus Basic' THEN 1
									END)
	  ,[GTX Basic] = COUNT(CASE WHEN pr.product='GTX Basic' THEN 1
									END)
	  ,[GTK 500] = COUNT(CASE WHEN pr.product='GTK 500' THEN 1
									END)
	  ,[MG Special] = COUNT(CASE WHEN pr.product='MG Special' THEN 1
									END)
FROM salespipeline sp
JOIN products pr
ON sp.product = pr.product

GROUP BY sp.deal_stage


/*4. Revenue generated by Region*/
SELECT pr.product
	  ,st.regional_office
	  ,product_count = COUNT(pr.product)
	  ,Revenue_generated = SUM(sp.close_value)
FROM salespipeline sp
JOIN products pr
ON pr.product = sp.product
JOIN salesteams st
ON st.sales_agent = sp.sales_agent
--WHERE sp.deal_stage = 'Won'
GROUP BY pr. product,st.regional_office
ORDER BY Revenue_generated DESC

